development:
  adapter: sqlite3
  host: localhost
  database: db/books_dev.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/books_test.sqlite3
  pool: 5
  timeout: 5000

#production:
#  adapter: postgresql
#  host: ec2-54-225-101-4.compute-1.amazonaws.com
#  database: d65vpcu05g232t
#  encoding: unicode
#  pool: 5
#  timeout: 5432
#  username: xcxjgjbheulldy
#  password: X93R-HY0mtILkl3KMDP1R9c2aJ